#=================================================================
# 对象存储配置
#=================================================================
storage:
  type: minio
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: xzf040116
    secretKey: xzf040116
